// The H3 take prompt, copied word for word from create-creator-takes-h3's
// plan_takes.py (TEMPLATE, MANNERISM and DEFAULT_DELIVERY): the prompt that held
// identity and eyeline across the reference builds. {identity}, {environment},
// {mannerism}, {delivery} and {dialogue} are filled per take.

export const H3_TEMPLATE = "A single continuous locked-off medium shot of <Subject 1>, with a natural front-camera recording look. The recording device and its support stay outside the frame.\n\n[Shot 1] The viewpoint is fixed at eye level, with the person facing the lens. No phone, camera, tripod or stand is visible. Chest-up framing, both shoulders in frame, head roughly centred with a little headroom, shot straight on. The hands are FREE and gesture while talking, one coming up and settling. Nobody holds the phone, there is no arm extended toward the camera. THE CAMERA DOES NOT MOVE: locked off, no handheld drift, no pan, no zoom, no reframing. One continuous unbroken shot.\n\nEYES STAY ON THE CAMERA LENS FOR THE WHOLE CLIP, from the very first frame to the very last, including the final word. Never glancing away, never looking down, never letting the gaze drift off the lens at the end of a sentence.\n\nTHE SUBJECT AND THE SET, unchanged from the first frame to the last, exactly as <Picture 1>: {identity}\n{environment}\nSKIN matches <Picture 1> exactly: visible pores, no smoothing, no plastic gloss, no over-sharpened edges. The light is the light in <Picture 1> and it does not change.\n{mannerism}\nHOW THEY SPEAK: {delivery}\nDIEGETIC SOUND: the voice and quiet room tone only.\nAUDIO RESTRICTIONS: no music, no beat, no sound design, no second voice, and no robotic, synthetic, text-to-speech, monotone or announcer-like delivery. The spoken audio contains ONLY the words inside the dialogue block. No stage directions and no markup is ever spoken aloud.\n\n<Subject 1> (S1) says, <d>[English] <inhale> {dialogue}</d>\n\nQuiet room around the voice. No music, no sound design, no second voice.\n";

export const H3_MANNERISM = "\n<Video 1> is a filmed reference person recorded the same way. Take from it ONLY the rhythm of natural speech, where the pauses fall and where the pace speeds up, and the small involuntary movement while talking: the head settling, the blink rate, the eyebrow lifts, the hands coming up and dropping back. Do NOT take the face, hair, clothes, room, lighting, framing or eyeline. The person is <Subject 1> from <Picture 1> and nobody else.\n";

export const H3_DEFAULT_DELIVERY = "natural and conversational, speaking directly to one viewer. Not presenting, not announcing, not reading. Sentences run together with almost no gap. Pitch falls on the last word of each sentence. Consonants relaxed, volume varying word to word.";
